{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    set -u
    function create_user_and_database() {
        local database=$1
        echo "  Creating database '$database'"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
            CREATE DATABASE $database;
            GRANT ALL PRIVILEGES ON DATABASE $database TO $POSTGRES_USER;
    EOSQL
    }
    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
        for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
            create_user_and_database $db
        done
    fi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_MULTIPLE_DATABASES
              value: "catalog_db,orders_db,users_db,notifications_db,analytics_db,,keycloak_db"
            # Bổ sung thêm biến môi trường PGDATA dưới đây ( để chỉ định thư mục dữ liệu của PostgreSQL)
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: dbport
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: init-script-vol
              mountPath: /docker-entrypoint-initdb.d
              # Mount đoạn script khởi tạo vào thư mục mà PostgreSQL sẽ tự động chạy khi container khởi động
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-script-vol
          configMap:
            name: postgres-init-script
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  {{- end }}