services:
  catalog-service:
    image: danghoang9704/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -Xss512k
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_ISSUER_URI=http://keycloak:9191/realms/bookstore
      - JWT_REQUIRED_AUDIENCE=catalog-service-api
      - API_GATEWAY_URL=http://api-gateway:8989/catalog
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - KEYCLOAK_API_CLIENT_ID=user-service-admin
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    image: danghoang9704/bookstore-order-service
    container_name: order-service
    environment:
        - BPL_JVM_THREAD_COUNT=50
        - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -Xss512k
        - SPRING_PROFILES_ACTIVE=docker
        - ORDERS_CATALOG_SERVICE_URL=http://api-gateway:8989/catalog
        - DB_URL=jdbc:postgresql://orders-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - RABBITMQ_HOST=bookstore-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=guest
        - KEYCLOAK_ISSUER_URI=http://keycloak:9191/realms/bookstore
        - JWT_REQUIRED_AUDIENCE=order-service-api
        - KEYCLOAK_API_CLIENT_ID=user-service-admin
        - API_GATEWAY_URL=http://api-gateway:8989/orders
        - MANAGEMENT_TRACING_ENABLED=true
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  notification-service:
    image: danghoang9704/bookstore-notification-service
    container_name: notification-service
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -Xss512k
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      notifications-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    image: danghoang9704/bookstore-api-gateway
    container_name: api-gateway
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -Xss512k
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - USER_SERVICE_URL=http://user-service:8084
      - REDIS_HOST=bookstore-redis
      - REDIS_PORT=6379
      - KEYCLOAK_ISSUER_URI=http://keycloak:9191/realms/bookstore
      - JWT_REQUIRED_AUDIENCE=api-gateway
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8989:8989"
    restart: unless-stopped
    depends_on:
      catalog-service:
        condition: service_started
      order-service:
        condition: service_started
      user-service:
        condition: service_started
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  user-service:
    image: danghoang9704/bookstore-user-service
    container_name: user-service
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -Xss512k
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://users-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_ISSUER_URI=http://keycloak:9191/realms/bookstore
      - KEYCLOAK_SERVER_URL=http://keycloak:9191
      - KEYCLOAK_REALM=bookstore
      - JWT_REQUIRED_AUDIENCE=user-service-api
      - KEYCLOAK_API_CLIENT_ID=user-service-api
      - KEYCLOAK_ADMIN_CLIENT_ID=user-service-admin
      - KEYCLOAK_ADMIN_CLIENT_SECRET=HqbZthuP7SpE5mxinaMkGURIlrRFj1EC
      - API_GATEWAY_URL=http://api-gateway:8989/users
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8084:8084"
    restart: unless-stopped
    depends_on:
      users-db:
        condition: service_healthy
      keycloak:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"
