spring.application.name=user-service
server.port=8084
server.shutdown=graceful

######## Actuator Configuration  #########
management.info.git.mode=full
management.endpoints.web.exposure.include=health,info,prometheus

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:45432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:9191/realms/bookstore}

# Keycloak server configuration
users.keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:9191}
users.keycloak.realm=${KEYCLOAK_REALM:bookstore}

# chỉ để token chứa audience user-service-api
security.jwt.required-audience=${JWT_REQUIRED_AUDIENCE:user-service-api}
users.keycloak.api-client-id=${KEYCLOAK_API_CLIENT_ID:user-service-api}

# Client này chỉ để backend gọi admin API.
users.keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:user-service-admin}
users.keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:Su2ewBLfHmdmvFRE5qRruSu68oCgRHED}

users.keycloak.default-role=USER
users.events-exchange=users-exchange

# Swagger UI OAuth2 configuration
# Config only use when you want to test API with Swagger UI and get access token from Keycloak server for user not gateway.
#springdoc.swagger-ui.oauth.client-id=${SWAGGER_CLIENT_ID:swagger-ui-client}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
swagger.api-gateway-url= ${API_GATEWAY_URL:http://localhost:8989/users}

# Resilience4j configuration
resilience4j.retry.instances.keycloak.max-attempts=3
resilience4j.retry.instances.keycloak.wait-duration=1s
resilience4j.retry.instances.keycloak.retry-exceptions=jakarta.ws.rs.ProcessingException,java.net.SocketTimeoutException
resilience4j.retry.instances.keycloak.ignore-exceptions=com.bookstore.user.web.exception.KeycloakUserAlreadyExistsException
