spring.application.name=order-service
server.port=8082
server.shutdown=graceful
server.tomcat.threads.max=50

######## Actuator Configuration  #########
management.info.git.mode=full
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

######## Database Configuration  #########
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:25432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

######## RabbitMQ Configuration  #########
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

######### Swagger Configuration  #########
swagger.api-gateway-url=${API_GATEWAY_URL:http://localhost:8989/orders}

# Swagger UI OAuth2 configuration
#springdoc.swagger-ui.oauth.client-id=${SWAGGER_CLIENT_ID:order-service-api}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

# Oauth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:9191/realms/bookstore}
security.jwt.required-audience=${JWT_REQUIRED_AUDIENCE:order-service-api}

### user-service-admin is only used for backend to call Keycloak admin API, its has on resource_access to get roles
orders.keycloak.client-id=${KEYCLOAK_API_CLIENT_ID:user-service-admin}

######## Order Service Configuration  #########
orders.catalog-service-url=${ORDERS_CATALOG_SERVICE_URL:http://localhost:8081}
#orders.catalog-service-url=http://localhost:8989/catalog
orders.order-events-exchange=orders-exchange
orders.new-orders-queue=new-orders
orders.delivered-orders-queue=delivered-orders
orders.cancelled-orders-queue=cancelled-orders
orders.error-orders-queue=error-orders

######## DLQ Configuration  #########
orders.dead-letter-exchange=orders-dlx
orders.new-orders-queue-retry=new-orders-retry
orders.new-orders-queue-dlq=new-orders-dlq
orders.delivered-queue-retry=delivered-orders-retry
orders.delivered-queue-dlq=delivered-orders-dlq
orders.cancelled-queue-retry=cancelled-orders-retry
orders.cancelled-queue-dlq=cancelled-orders-dlq
orders.error-queue-retry=error-orders-retry
orders.error-queue-dlq=error-orders-dlq
orders.retry-ttl=10000

orders.publish-order-events-job-cron=*/5 * * * * *
orders.new-orders-job-cron=*/10 * * * * *
orders.new-orders-job-delay= 60000
orders.outbox.max-retry= 5
######## Resilience4j Configuration  #########
resilience4j.retry.backends.catalogService.max-attempts=3
resilience4j.retry.backends.catalogService.wait-duration=1s

resilience4j.circuitbreaker.backends.catalog-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.backends.catalog-service.sliding-window-size=6
resilience4j.circuitbreaker.backends.catalog-service.minimum-number-of-calls=4
resilience4j.circuitbreaker.backends.catalog-service.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.backends.catalog-service.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.backends.catalog-service.failure-rate-threshold=50

resilience4j.retry.instances.rabbit.max-attempts=3
resilience4j.retry.instances.rabbit.wait-duration=2s

logging.pattern.level="%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"