apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
    service: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  strategy:
    type: RollingUpdate # Use RollingUpdate strategy for zero downtime deployments
    rollingUpdate:
      maxSurge: 1 # Allow one additional pod to be created during the update
      maxUnavailable: 0 # Ensure that no pods are unavailable during the update
  selector:
    matchLabels:
      service: api-gateway
  template:
    metadata:
      labels:
        service: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: {{ .Values.apiGateway.port | quote }}
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.imageUsername }}/bookstore-api-gateway:{{ .Values.apiGateway.imageTag }}"
          # Sẽ ghi đè vào giá trị latest khai báo trong values.
          # Sử dụng chuẩn đên từng commit SHA để đảm bảo tính nhất quán của image khi triển khai trên GKE của từng service
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.apiGateway.port }}
          env:
            - name: JWT_REQUIRED_AUDIENCE
              value: "api-gateway"
            - name: SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE
              value: {{ .Values.lifecycle.timeoutPerShutdownPhase | quote }}
            - name: SERVER_SHUTDOWN
              value: "graceful"
          envFrom:
            - configMapRef:
                name: bookstore-configmap
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep {{ .Values.lifecycle.preStopSleepSeconds }}"]
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.apiGateway.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.apiGateway.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
  selector:
    service: api-gateway