apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-configmap
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
data:
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuer | quote }}
  KEYCLOAK_API_CLIENT_ID: "user-service-admin"

  DB_USERNAME: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  API_GATEWAY_URL: {{ .Values.global.apiGatewayUrl | quote }}

  CATALOG_SERVICE_URL: "http://catalog-service:8081"
  ORDER_SERVICE_URL: "http://order-service:8082"
  USER_SERVICE_URL: "http://user-service:8084"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8085"

  MANAGEMENT_TRACING_ENABLED: {{ .Values.tracing.enabled | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.tracing.zipkinEndpoint | quote }}