apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bookstore-selfsigned-issuer
spec:
  selfSigned: {} # Ra lệnh cho cert-manager tự tạo chứng chỉ không cần internet

# Cách thức hoạt động lúc này: Khi bạn chạy Helm cài đặt,
# Cert-Manager thấy cấu hình bookstore-selfsigned-issuer,
# nó sẽ tự động ký một chứng chỉ mã hóa cho bookstore.local và keycloak.local,
# sau đó đóng gói thành một Kubernetes Secret có tên là bookstore-tls-local-secret.
# Ingress sẽ nhặt Secret này lên để bật cổng HTTPS (https://bookstore.local).