apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  keycloak-admin-client-secret: {{ .Values.secrets.keycloakAdminClientSecret | b64enc | quote }}