global:
  imageRegistry: "docker.io"
  imageUsername: "danghoang9704"
  keycloakIssuer: "http://keycloak.local/realms/bookstore" # Sử dụng HTTP
  apiGatewayUrl: "http://bookstore.local" # Sử dụng HTTP
  ingressClassName: "nginx"
  imagePullPolicy: "Always"
  hostAliases:
    - ip: "34.118.237.242" # IP Ingress
      hostnames:
        - "keycloak.local"
  # Cấu hình Hostname dùng chung để trỏ file hosts local về IP GKE
  apiGatewayHost: "bookstore.local"
  keycloakHost: "keycloak.local"
  # TẮT TLS trên GKE
  tls:
    enabled: false
    secretName: "bookstore-tls-prod-secret"
    certIssuer: ""
tracing:
  enabled: "false"
  zipkinEndpoint: "http://tempo:9411"
lifecycle:
  timeoutPerShutdownPhase: "30s"
  preStopSleepSeconds: 15
apiGateway:
  replicaCount: 1
  port: 8989
  imageTag: "6ec9705" # Default để "latest" cho GKE, sẽ cập nhật trỏ về biến imageTag riêng của từng service
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: false
#    enabled: true
#    minReplicas: 2
#    maxReplicas: 5
#    targetCPUUtilizationPercentage: 70

catalogService:
  replicaCount: 1
  port: 8081
  imageTag: "latest"
  dbUrl: "jdbc:postgresql://postgres:5432/catalog_db"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 1Gi
  autoscaling:
    enabled: false
#    enabled: true
#    minReplicas: 2
#    maxReplicas: 5
#    targetCPUUtilizationPercentage: 70

orderService:
  replicaCount: 1
  port: 8082
  imageTag: "latest"
  dbUrl: "jdbc:postgresql://postgres:5432/orders_db"
  catalogServiceUrl: "http://catalog-service:8081"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 1Gi
  autoscaling:
    enabled: false
#    enabled: true
#    minReplicas: 2
#    maxReplicas: 5
#    targetCPUUtilizationPercentage: 70

userService:
  replicaCount: 1
  port: 8084
  imageTag: "latest"
  dbUrl: "jdbc:postgresql://postgres:5432/users_db"
  keycloakServerUrl: "http://keycloak:9191"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: false
notificationService:
  replicaCount: 1
  port: 8083
  imageTag: "latest"
  dbUrl: "jdbc:postgresql://postgres:5432/notifications_db"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 768Mi
  autoscaling:
    enabled: false
analyticsService:
  replicaCount: 1
  port: 8085
  imageTag: "latest"
  dbUrl: "jdbc:postgresql://postgres:5432/analytics_db"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 768Mi
  autoscaling:
    enabled: false
secrets:
  databasePassword: "superSecurePassword123"
  keycloakAdminClientSecret: "HqbZthuP7SpE5mxinaMkGURIlrRFj1EC"
